[DATABASE]
URL_USERS_PRIMARY = 'sqlite+aiosqlite:///database/dbs/primary/mount/users.db'
URL_GAMES_PRIMARY = 'sqlite+aiosqlite:///database/dbs/primary/mount/games.db'

[REDIS]
HOST = 'localhost'
PORT = 6379